//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKER
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker1
    {
        public int id_worker { get; set; }
        public string name { get; set; }
        public string post { get; set; }
        public Nullable<int> exp { get; set; }
    }
}
